version: '3.9' 

services:
  postgres:
    image: postgres:15 
    container_name: fortuna 
    environment: 
      POSTGRES_USER: ebod
      POSTGRES_PASSWORD: Awaken1312
      POSTGRES_DB: fortuna
    ports:  
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 
